name: Build
on:
  push:
  release:
    types: [published]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Build
        run: |
          npm run build
  publish:
    needs: [check]
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
          mv build .build
      - name: Publish
        run: |
          tag=${GITHUB_REF#refs/tags/}
          git checkout gh-pages
          git rm -rf *
          mv .build/* .
          rm -rf .build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add build
          git commit -m "Add build for version $tag"
          git push
